Repository ucsb-cs156-f23/proj-happycows-f23-5pm-1, pull requests merged in 2023-11, with the labels that each got.

#17 Removed Sold Cow Toast
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: FIXME-See Code Review

#20 lli - Added UI changes and tests for Instructor Report Page
  frontend/src/main/components/Reports/ReportHeaderTable.js
  frontend/src/main/components/Reports/ReportLineTable.js
  frontend/src/main/components/Reports/ReportTable.js
  frontend/src/tests/components/Reports/ReportHeaderTable.test.js
  frontend/src/tests/components/Reports/ReportLineTable.test.js
  frontend/src/tests/components/Reports/ReportTable.test.js
Labels: 10

#19 Harold ux improvements to leaderboard page 2
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 10, Merge Candidate

#21 Added explanation description to the fields within the Create Commons page
  frontend/package.json
  frontend/src/main/components/Commons/CommonsForm.js
Labels: 5, Merge Candidate

#27 Refactor CommonList component with a default UI
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/tests/components/Commons/CommonsList.test.js
Labels: 10

#29 Changed Icons for Chat Toggle Button
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5

#25 Admin Commons List Reformatted to Minimize Horizontal Scrolling
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminListCommonPage.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: 5

#35 Vl chat room ux UI
  frontend/src/main/components/Chat/ChatMessageDisplay.js
  frontend/src/tests/components/Chat/ChatDisplay.test.js
  frontend/src/tests/components/Chat/ChatMessageDisplay.test.js
Labels: 10
